### ISSUE TITLE
P2P

### ISSUE THREAD

**Issue by AbdelrhmanAmin** [vichuge/6-the-next-web#1]
Remove the classes from head link
https://github.com/vichuge/6-the-next-web/blob/76cb1e302bdafe708911eb2e806571312919dd81/index.html#L9-L15

**Comment by VanessaAoki** [comment]
Great project!! Looks almost like the original one!

I do have some little suggestions:
1. You should make all icons on the footer clickable (my tse asked for this change);
2. Make the top navbar sticky;
3. Mobile version: the first articles are not working properly, the second and the third articles are sized differently;
4. Mobile version: the navbar is also not working properly;

![Screenshot from 2020-11-19 11-32-39](https://user-images.githubusercontent.com/66967274/99679745-0d644e00-2a5b-11eb-9f6a-bd90dfb924b6.png)

## Keep up the good work!
